POST http://localhost:3333/goals
Content-Type: application/json

{
  "title": "Swim",
  "desiredWeeklyFrequency": 2
}

#############

GET http://localhost:3333/pending-goals

#############

POST http://localhost:3333/completions
Content-Type: application/json

{
  "goalId": "ipxk5tulz2i8udk1bebja91x"
}

#############

GET http://localhost:3333/summary

#############